French Adjectives Transformation
GEM-benchmark/NL-Augmenter pull request #249
Opened 2021-08-31 15:11 UTC by Louanes1

2021-09-02 20:23 UTC, Louanes1 commented
The pytest suceed when I try to run it locally, it shouldn't fail in the build : 
![image](https://user-images.githubusercontent.com/79848841/131911013-7016b3d3-0215-4e5f-9abb-12d696788c9a.png)

2021-09-18 18:41 UTC, gxywang requested changes
Hi @Louanes1, I'm one of the assigned reviewers for your transformation. Below is my general review, see comments for more specific feedback.

Correctness: Failed the build with an AssertionError. I saw the comment regarding passing the unit test locally. Maybe see if your local version is up-to-date? Otherwise, I'm also unsure why it failed.
Interface: Looks good.
Applicable Tasks & Keywords: Task types have been added, missing keywords.
Specificity: The task is specific to text classification, generation, and tagging.
Novelty: This transformation is not implemented in NL-Augmenter already.
Adding New Libraries: All added to requirements, only nltk's version has not been specified.
Description: Readme looks good.
Data and code source: None. Should add a sentence stating it was fully created by author (or cite relevant sources).
Paraphrasers and Data Augmenters: N/A
Test Cases: 3 examples added, 5 recommended.
Evaluating Robustness: Evaluation has not been provided.
Languages other than English: French.
Decent Programming Practise: No docstrings, consider adding some.

If anything needs clarification, please let me know. Otherwise, thanks for the contribution!

2021-09-18 18:41 UTC, gxywang commented on transformations/french_synonym_adjectives_transformation/README.md
> +This tool does not take the general context into account, sometimes, the ouput will not match the general sense of te sentence.
misspelling: *the

If possible, the results of the evaluate.py test should be added to the Readme as well.

2021-09-18 18:41 UTC, gxywang commented on transformations/french_synonym_adjectives_transformation/README.md
> +Authors : Lisa Barthe and Louanes Hamla from Fablab by Inetum in Paris
Emails should be added to the authors, please.

2021-09-18 18:41 UTC, gxywang commented on transformations/french_synonym_adjectives_transformation/test.json
> +
It is recommended to include at least 5 examples here.

2021-09-18 18:41 UTC, gxywang commented on transformations/french_synonym_adjectives_transformation/transformation.py
> +import nltk
nltk is imported twice.

2021-09-18 18:41 UTC, gxywang commented on transformations/french_synonym_adjectives_transformation/transformation.py
> +
Relavent [keywords ](https://github.com/GEM-benchmark/NL-Augmenter/blob/main/docs/keywords.md) should also be added.

2021-09-18 18:41 UTC, gxywang commented on transformations/french_synonym_adjectives_transformation/requirements.txt
> +nltk
Should nltk's version be specified as well?

2021-09-18 18:41 UTC, gxywang commented on transformations/french_synonym_adjectives_transformation/transformation.py
> +        print("perturbed text inside of class",perturbed_texts)
May want to delete this print line.

2021-09-21 13:40 UTC, mille-s commented
Should there be just one transformation for Verbs https://github.com/GEM-benchmark/NL-Augmenter/pull/250, Nouns https://github.com/GEM-benchmark/NL-Augmenter/pull/247 and Adjectives, since the method seems to be the same? The transformation could be called "Lexical susbstitutions for French".

2021-09-29 22:12 UTC, kaustubhdhole commented
Agree with @mille-s  above. By default, you can return all (nouns,adjectives and adverbs) and still have it parametrized. Since we are tabulating the PRs, I am closing this. Please try to address all the suggested changes of the reviews in all the 3 PRs to https://github.com/GEM-benchmark/NL-Augmenter/pull/250

2021-09-29 22:12 UTC, closed without merging