Question-Answer Transformation using a Quora Question Paraphraser
GEM-benchmark/NL-Augmenter pull request #43
Opened 2021-06-18 21:39 UTC by kaustubhdhole

1. This transformation creates new QA pairs by generating question paraphrases from a T5 model fine-tuned on Quora Question pairs.   
2. This transformation acts like a paraphrase generator. Generated questions can have a very different surface form from the original question making it a strong paraphrase generator. A T5 model was fine tuned on the Quora Question Pairs dataset and is being used to generate question paraphrases.
3. Here is the performance of the model mrm8488/bert-tiny-5-finetuned-squadv2 on the validation[:20%] split of the squad dataset
The accuracy on a subset of squad = 60.31220435193945
The accuracy on its perturbed set generated from QuoraT5QaPairGenerator = 47.161778618732264
This ~13% would also be attributed to paraphrasing errors.

2021-07-07 17:54 UTC, sebastianGehrmann requested changes

2021-07-07 17:54 UTC, sebastianGehrmann commented on transformations/quora_trained_t5_for_qa/README.md
> +This transformation creates new QA pairs by generating question paraphrases from a T5 model fine-tuned on Quora Question pairs.
#BenderRule

2021-07-07 17:54 UTC, sebastianGehrmann commented on transformations/quora_trained_t5_for_qa/__init__.py
> +from .transformation import *
nit: new newline at the end of the file.

2021-07-07 17:54 UTC, sebastianGehrmann commented on transformations/quora_trained_t5_for_qa/transformation.py
> +"""The T5 model and code has been taken from https://huggingface.co/ramsrigouthamg/t5_paraphraser. The test cases
This comment reads a bit strange. Maybe follow the convention to write one sentence high-level before adding details.

2021-07-07 17:54 UTC, sebastianGehrmann commented on transformations/quora_trained_t5_for_qa/transformation.py
> +class QuoraT5QaPairGenerator(QuestionAnswerOperation):
Doctrings please :)

2021-07-07 17:54 UTC, sebastianGehrmann commented on transformations/quora_trained_t5_for_qa/transformation.py
> +        self.num_return_sequences = 3
Making this configurable could help.

2021-07-07 17:54 UTC, sebastianGehrmann commented on transformations/quora_trained_t5_for_qa/transformation.py
> +        beam_outputs = self.model.generate(
It could be a helpful addition to add a filtering step of some sort for cases where the outputs are of insufficient quality.

2021-07-07 17:54 UTC, sebastianGehrmann commented on transformations/quora_trained_t5_for_qa/transformation.py
> +            top_k=120,
120 is quite a bit, maybe reducing to 40 would lead to better quality (albeit less diversity.)

2021-07-07 17:54 UTC, sebastianGehrmann commented on transformations/quora_trained_t5_for_qa/transformation.py
> +                unique_question_paraprases.append(sent)
maybe rename to clarify that this ensures that the paraphrase != original instead of `unique`?

2021-07-27 07:34 UTC, kaustubhdhole commented
Thanks @sebastianGehrmann very much for your comments. I've fixed those.

2021-07-27 07:47 UTC, merged