Add "Greetings and Farewells" transformation
GEM-benchmark/NL-Augmenter pull request #88
Opened 2021-06-29 15:20 UTC by paulozip

Hello everyone. Congratulations on this awesome project. I think it will be a big contribution to the community.

I created this transformation that **basically creates some text variants and perturbations on words and expressions related to greetings and farewells**. For instance, sentences containing words like "Hi!" or "What's up?" will have these words replaced by similar ones, like "Howdy" or "Good morning". The same behavior will be done for farewells and special cases (e.g. "It's nice to meet you" or "How's it going?").

**The main goal of this transformation is to tackle the robustness of text classification/generation models when faced with perturbations**.

Let me know if you need more details about the implementation.

2021-07-01 03:19 UTC, samsontmr requested changes
Thanks for the contribution! This generally looks good. I noticed that you're located in Brazil; it would be great if you could implement this transformation for any other languages you speak!

2021-07-01 03:19 UTC, samsontmr commented on transformations/greetings_and_farewells/transformation.py
> +    random.seed(seed)
I believe `random.seed()` needs to be called each time before `random.choice()`. I would recommend generating a random integer as a seed for each `random.choice()` call using this seed to increase diversity in the test examples while remaining reproducible.

2021-07-06 17:01 UTC, kaustubhdhole commented
Hi @paulozip, thank you for you changes! Here is my overall review:

Build: passes
Interface: Only tagging won't be applicable since the number of tokens are changing in some cases.
Specificity: This change is specific.
Paraphrasing: I think the coverage is very low.
Description: README describes properly.
Evaluating Robustness: No evaluation has been conducted. 
Test cases: 5 have been added.

I find it fine overall, please remove TEXT_TAGGING and if possible, add more variations to increase coverage.

Thanks for your effort!

2021-07-11 04:34 UTC, samsontmr approved these changes
Approving this, the extension to other languages can be done in a separate PR.

2021-08-08 04:01 UTC, kaustubhdhole approved these changes

2021-08-08 04:01 UTC, merged